"""Composition Library — selects Renderer Approach / Strategy (DOM architecture).

Field ``section_order`` remains for ClassicRenderer only.
Named Strategies own their HTML trees.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class CompositionConcept:
    """One complete page composition — a designer choice, not a shuffle."""

    id: str
    label: str
    section_order: tuple[str, ...]
    hero_layouts: tuple[str, ...]
    component: str  # A|B|C
    layout_seed: str  # preferred L-profile family
    niche_affinity: tuple[str, ...]  # niches that love this form
    anti_predictable: bool = True  # True = breaks classic funnel rhythm
    mood: str = ""
    notes: str = ""

    def as_dict(self) -> dict[str, Any]:
        from app.factory.renderers.registry import (
            COMPOSITION_TO_APPROACH,
            COMPOSITION_TO_STRATEGY,
        )

        approach = COMPOSITION_TO_APPROACH.get(self.id, "")
        return {
            "id": self.id,
            "label": self.label,
            "section_order": list(self.section_order),
            "hero_layouts": list(self.hero_layouts),
            "component": self.component,
            "layout_seed": self.layout_seed,
            "niche_affinity": list(self.niche_affinity),
            "anti_predictable": self.anti_predictable,
            "mood": self.mood,
            "notes": self.notes,
            "approach": approach,
            "renderer_strategy": COMPOSITION_TO_STRATEGY.get(self.id, "")
            or approach,
        }


# Card-like blocks — consecutive runs of these = "too predictable"
CARDY_SECTIONS = frozenset(
    {"services", "benefits", "trust", "process", "stats", "reviews", "info"}
)

# Classic boring funnel fingerprint (normalized)
_BORING_PREFIXES = (
    ("info", "stats", "services", "mid_cta", "benefits"),
    ("info", "stats", "catalog", "services", "mid_cta"),
    ("info", "trust", "stats", "catalog", "benefits", "services"),
)


COMPOSITION_LIBRARY: dict[str, CompositionConcept] = {
    "magazine": CompositionConcept(
        id="magazine",
        label="Magazine editorial",
        section_order=(
            "about",
            "gallery",
            "services",
            "mid_cta",
            "showcase",
            "benefits",
            "trust",
            "process",
            "stats",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("B", "D", "C"),
        component="C",
        layout_seed="L6",
        niche_affinity=("psychology", "law", "beauty", "photography"),
        mood="editorial quiet",
        notes="Story first, services as feature spread",
    ),
    "split": CompositionConcept(
        id="split",
        label="Split dialogue",
        section_order=(
            "about",
            "services",
            "gallery",
            "mid_cta",
            "trust",
            "benefits",
            "process",
            "showcase",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("A", "E", "D"),
        component="A",
        layout_seed="L2",
        niche_affinity=("psychology", "law", "dental", "accounting"),
        mood="two-column calm",
    ),
    "asymmetrical": CompositionConcept(
        id="asymmetrical",
        label="Asymmetrical stage",
        section_order=(
            "gallery",
            "about",
            "mid_cta",
            "services",
            "showcase",
            "trust",
            "benefits",
            "process",
            "stats",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "E", "B"),
        component="A",
        layout_seed="L3",
        niche_affinity=("psychology", "beauty", "photography", "fashion"),
        mood="uneven breathing",
    ),
    "editorial": CompositionConcept(
        id="editorial",
        label="Long-form editorial",
        section_order=(
            "about",
            "benefits",
            "gallery",
            "services",
            "mid_cta",
            "process",
            "trust",
            "showcase",
            "faq",
            "reviews",
            "calculator",
            "maps",
            "contact",
        ),
        hero_layouts=("C", "B", "D"),
        component="C",
        layout_seed="L6",
        niche_affinity=("psychology", "law", "realestate"),
        mood="essay + proof",
    ),
    "cinematic": CompositionConcept(
        id="cinematic",
        label="Cinematic immersion",
        section_order=(
            "showcase",
            "mid_cta",
            "about",
            "gallery",
            "services",
            "trust",
            "benefits",
            "process",
            "faq",
            "reviews",
            "maps",
            "late_cta",
            "contact",
        ),
        hero_layouts=("D", "B", "F"),
        component="A",
        layout_seed="L3",
        niche_affinity=("psychology", "beauty", "restaurant", "realestate"),
        mood="film still then story",
    ),
    "cards_first": CompositionConcept(
        id="cards_first",
        label="Offers first",
        section_order=(
            "services",
            "mid_cta",
            "gallery",
            "about",
            "benefits",
            "trust",
            "process",
            "showcase",
            "stats",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("A", "C", "E"),
        component="B",
        layout_seed="L1",
        niche_affinity=("dental", "auto", "appliance", "fitness"),
        mood="commerce clarity",
        anti_predictable=False,  # closer to funnel — score lower for Premium
    ),
    "immersive": CompositionConcept(
        id="immersive",
        label="Immersive continuum",
        section_order=(
            "gallery",
            "showcase",
            "about",
            "mid_cta",
            "services",
            "process",
            "trust",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "late_cta",
            "contact",
        ),
        hero_layouts=("D", "F", "B"),
        component="A",
        layout_seed="L3",
        niche_affinity=("psychology", "beauty", "photography", "energy"),
        mood="one continuous scene",
    ),
    "gallery": CompositionConcept(
        id="gallery",
        label="Gallery lead",
        section_order=(
            "gallery",
            "showcase",
            "services",
            "mid_cta",
            "about",
            "trust",
            "benefits",
            "process",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("E", "A", "D"),
        component="A",
        layout_seed="L3",
        niche_affinity=("beauty", "photography", "fashion", "restaurant"),
        mood="visual proof first",
    ),
    "storytelling": CompositionConcept(
        id="storytelling",
        label="Story arc",
        section_order=(
            "about",
            "process",
            "gallery",
            "mid_cta",
            "services",
            "benefits",
            "trust",
            "showcase",
            "faq",
            "reviews",
            "maps",
            "late_cta",
            "contact",
        ),
        hero_layouts=("D", "C", "B"),
        component="C",
        layout_seed="L6",
        niche_affinity=("psychology", "law", "handwerk", "green"),
        mood="journey chapters",
    ),
    "timeline": CompositionConcept(
        id="timeline",
        label="Process timeline",
        section_order=(
            "process",
            "about",
            "mid_cta",
            "services",
            "gallery",
            "trust",
            "benefits",
            "showcase",
            "stats",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("C", "A", "D"),
        component="B",
        layout_seed="L2",
        niche_affinity=("psychology", "dental", "law", "energy"),
        mood="how it works as spine",
    ),
    "trust_cascade": CompositionConcept(
        id="trust_cascade",
        label="Trust cascade",
        section_order=(
            "trust",
            "about",
            "reviews",
            "services",
            "mid_cta",
            "gallery",
            "benefits",
            "process",
            "faq",
            "maps",
            "contact",
        ),
        hero_layouts=("C", "A", "D"),
        component="C",
        layout_seed="L2",
        niche_affinity=("psychology", "dental", "law", "accounting"),
        mood="credibility before offer",
    ),
    "whisper": CompositionConcept(
        id="whisper",
        label="Whisper luxury",
        section_order=(
            "about",
            "mid_cta",
            "gallery",
            "services",
            "showcase",
            "trust",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "B", "F"),
        component="C",
        layout_seed="L6",
        niche_affinity=("psychology", "beauty", "law", "realestate"),
        mood="few words, deep space",
    ),
    "manifesto": CompositionConcept(
        id="manifesto",
        label="Manifesto then craft",
        section_order=(
            "about",
            "benefits",
            "mid_cta",
            "gallery",
            "services",
            "process",
            "trust",
            "showcase",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("B", "D", "C"),
        component="C",
        layout_seed="L6",
        niche_affinity=("psychology", "green", "energy", "handwerk"),
        mood="belief → proof → offer",
    ),
    "atelier": CompositionConcept(
        id="atelier",
        label="Atelier workshop",
        section_order=(
            "showcase",
            "process",
            "gallery",
            "services",
            "mid_cta",
            "about",
            "trust",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("E", "D", "A"),
        component="A",
        layout_seed="L3",
        niche_affinity=("beauty", "handwerk", "photography", "fashion"),
        mood="craft visible",
    ),
    "sanctuary": CompositionConcept(
        id="sanctuary",
        label="Sanctuary calm",
        section_order=(
            "about",
            "gallery",
            "trust",
            "mid_cta",
            "services",
            "process",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "A", "C"),
        component="A",
        layout_seed="L2",
        niche_affinity=("psychology", "dental", "beauty", "green"),
        mood="safe room energy",
    ),
    "pulse": CompositionConcept(
        id="pulse",
        label="Pulse rhythm",
        section_order=(
            "stats",
            "gallery",
            "services",
            "mid_cta",
            "about",
            "showcase",
            "trust",
            "process",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "late_cta",
            "contact",
        ),
        hero_layouts=("B", "D", "F"),
        component="B",
        layout_seed="L4",
        niche_affinity=("fitness", "auto", "energy", "restaurant"),
        mood="metric → image → offer",
    ),
    "folio": CompositionConcept(
        id="folio",
        label="Portfolio folio",
        section_order=(
            "gallery",
            "about",
            "showcase",
            "services",
            "mid_cta",
            "trust",
            "benefits",
            "process",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("E", "B", "D"),
        component="A",
        layout_seed="L3",
        niche_affinity=("photography", "fashion", "beauty", "architecture"),
        mood="work speaks",
    ),
    "ritual": CompositionConcept(
        id="ritual",
        label="Ritual steps",
        section_order=(
            "process",
            "gallery",
            "services",
            "mid_cta",
            "about",
            "trust",
            "benefits",
            "showcase",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "C", "A"),
        component="C",
        layout_seed="L6",
        niche_affinity=("psychology", "beauty", "restaurant", "fitness"),
        mood="ceremony of care",
    ),
    "horizon": CompositionConcept(
        id="horizon",
        label="Horizon reveal",
        section_order=(
            "showcase",
            "about",
            "gallery",
            "mid_cta",
            "services",
            "benefits",
            "trust",
            "process",
            "faq",
            "reviews",
            "maps",
            "late_cta",
            "contact",
        ),
        hero_layouts=("D", "F", "B"),
        component="A",
        layout_seed="L3",
        niche_affinity=("psychology", "realestate", "energy", "green"),
        mood="wide open then intimate",
    ),
    "dialogue": CompositionConcept(
        id="dialogue",
        label="FAQ dialogue early",
        section_order=(
            "faq",
            "about",
            "services",
            "mid_cta",
            "gallery",
            "trust",
            "benefits",
            "process",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("C", "A", "D"),
        component="C",
        layout_seed="L2",
        niche_affinity=("psychology", "dental", "law", "accounting"),
        mood="answer fears early",
    ),
    "boutique": CompositionConcept(
        id="boutique",
        label="Boutique curation",
        section_order=(
            "showcase",
            "services",
            "gallery",
            "mid_cta",
            "about",
            "trust",
            "benefits",
            "process",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("E", "D", "A"),
        component="A",
        layout_seed="L3",
        niche_affinity=("beauty", "fashion", "restaurant", "psychology"),
        mood="curated selection",
    ),
    "garden": CompositionConcept(
        id="garden",
        label="Garden path",
        section_order=(
            "gallery",
            "about",
            "process",
            "mid_cta",
            "services",
            "benefits",
            "trust",
            "showcase",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "A", "E"),
        component="A",
        layout_seed="L6",
        niche_affinity=("psychology", "green", "beauty"),
        mood="nature therapy walk",
    ),
    "chamber": CompositionConcept(
        id="chamber",
        label="Private chamber",
        section_order=(
            "about",
            "trust",
            "mid_cta",
            "services",
            "gallery",
            "process",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "C", "B"),
        component="C",
        layout_seed="L2",
        niche_affinity=("psychology", "law", "dental"),
        mood="confidential intimacy",
    ),
    "overture": CompositionConcept(
        id="overture",
        label="Overture then movement",
        section_order=(
            "showcase",
            "stats",
            "about",
            "gallery",
            "mid_cta",
            "services",
            "trust",
            "process",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "late_cta",
            "contact",
        ),
        hero_layouts=("B", "D", "F"),
        component="A",
        layout_seed="L4",
        niche_affinity=("psychology", "restaurant", "realestate", "energy"),
        mood="overture → movements",
    ),
    # --- Expansion toward 50+ distinct rhythms (Digital Creative Studio) ---
    "bento": CompositionConcept(
        id="bento",
        label="Bento mosaic",
        section_order=(
            "showcase",
            "gallery",
            "services",
            "stats",
            "mid_cta",
            "about",
            "benefits",
            "trust",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("E", "D", "A"),
        component="A",
        layout_seed="L3",
        niche_affinity=("technology", "saas", "creative", "beauty"),
        mood="modular mosaic",
    ),
    "floating": CompositionConcept(
        id="floating",
        label="Floating islands",
        section_order=(
            "about",
            "showcase",
            "mid_cta",
            "gallery",
            "services",
            "process",
            "trust",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "B", "F"),
        component="C",
        layout_seed="L6",
        niche_affinity=("psychology", "beauty", "fashion"),
        mood="islands in air",
    ),
    "diagonal": CompositionConcept(
        id="diagonal",
        label="Diagonal energy",
        section_order=(
            "showcase",
            "about",
            "services",
            "gallery",
            "mid_cta",
            "stats",
            "process",
            "trust",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("B", "F", "D"),
        component="A",
        layout_seed="L4",
        niche_affinity=("auto", "fitness", "technology", "handwerk"),
        mood="angled momentum",
    ),
    "visual_first": CompositionConcept(
        id="visual_first",
        label="Visual first",
        section_order=(
            "gallery",
            "showcase",
            "about",
            "mid_cta",
            "services",
            "trust",
            "process",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "B", "E"),
        component="A",
        layout_seed="L6",
        niche_affinity=("photography", "beauty", "restaurant", "fashion"),
        mood="image leads story",
    ),
    "product_first": CompositionConcept(
        id="product_first",
        label="Product first",
        section_order=(
            "catalog",
            "showcase",
            "services",
            "mid_cta",
            "gallery",
            "about",
            "trust",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("E", "A", "D"),
        component="A",
        layout_seed="L3",
        niche_affinity=("fashion", "beauty", "restaurant", "handwerk"),
        mood="offer before essay",
    ),
    "narrative": CompositionConcept(
        id="narrative",
        label="Long-form narrative",
        section_order=(
            "about",
            "process",
            "gallery",
            "mid_cta",
            "services",
            "showcase",
            "trust",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "late_cta",
            "contact",
        ),
        hero_layouts=("C", "D", "A"),
        component="C",
        layout_seed="L2",
        niche_affinity=("psychology", "law", "dental"),
        mood="chaptered story",
    ),
    "luxury_brand": CompositionConcept(
        id="luxury_brand",
        label="Luxury brand",
        section_order=(
            "showcase",
            "about",
            "gallery",
            "mid_cta",
            "services",
            "trust",
            "process",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "B", "F"),
        component="C",
        layout_seed="L6",
        niche_affinity=("fashion", "beauty", "jewelry", "realestate"),
        mood="quiet luxury brand",
    ),
    "corporate": CompositionConcept(
        id="corporate",
        label="Corporate clarity",
        section_order=(
            "about",
            "stats",
            "services",
            "mid_cta",
            "trust",
            "process",
            "benefits",
            "showcase",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("C", "A", "E"),
        component="B",
        layout_seed="L1",
        niche_affinity=("law", "accounting", "it", "energy"),
        mood="boardroom clarity",
        anti_predictable=False,
    ),
    "modern": CompositionConcept(
        id="modern",
        label="Modern precision",
        section_order=(
            "stats",
            "services",
            "showcase",
            "mid_cta",
            "about",
            "gallery",
            "trust",
            "process",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("A", "E", "D"),
        component="A",
        layout_seed="L5",
        niche_affinity=("technology", "dental", "computer", "saas"),
        mood="clean modern",
    ),
    "creative": CompositionConcept(
        id="creative",
        label="Creative studio",
        section_order=(
            "gallery",
            "showcase",
            "about",
            "services",
            "mid_cta",
            "process",
            "trust",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("B", "D", "F"),
        component="A",
        layout_seed="L4",
        niche_affinity=("photography", "creative", "beauty"),
        mood="studio portfolio energy",
    ),
    "healthcare": CompositionConcept(
        id="healthcare",
        label="Healthcare calm",
        section_order=(
            "trust",
            "about",
            "services",
            "mid_cta",
            "process",
            "gallery",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("C", "A", "D"),
        component="C",
        layout_seed="L2",
        niche_affinity=("dental", "psychology", "healthcare"),
        mood="clinical calm trust",
    ),
    "nature": CompositionConcept(
        id="nature",
        label="Nature immersion",
        section_order=(
            "gallery",
            "about",
            "showcase",
            "mid_cta",
            "services",
            "process",
            "benefits",
            "trust",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "E", "A"),
        component="A",
        layout_seed="L6",
        niche_affinity=("psychology", "green", "beauty", "restaurant"),
        mood="outdoor breath",
    ),
    "tech_stack": CompositionConcept(
        id="tech_stack",
        label="Tech stack narrative",
        section_order=(
            "showcase",
            "stats",
            "services",
            "mid_cta",
            "process",
            "about",
            "trust",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("B", "F", "A"),
        component="A",
        layout_seed="L5",
        niche_affinity=("technology", "computer", "it", "saas"),
        mood="product narrative",
    ),
    "spotlight": CompositionConcept(
        id="spotlight",
        label="Spotlight feature",
        section_order=(
            "showcase",
            "mid_cta",
            "about",
            "gallery",
            "services",
            "trust",
            "process",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "B", "E"),
        component="C",
        layout_seed="L6",
        niche_affinity=("psychology", "beauty", "restaurant", "fashion"),
        mood="one feature owns the fold",
    ),
    "cascade": CompositionConcept(
        id="cascade",
        label="Cascade reveals",
        section_order=(
            "about",
            "gallery",
            "process",
            "mid_cta",
            "services",
            "showcase",
            "trust",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("A", "D", "C"),
        component="A",
        layout_seed="L2",
        niche_affinity=("psychology", "law", "dental"),
        mood="sequential reveal",
    ),
    "mirror": CompositionConcept(
        id="mirror",
        label="Mirror dialogue",
        section_order=(
            "about",
            "gallery",
            "services",
            "mid_cta",
            "trust",
            "process",
            "benefits",
            "showcase",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("A", "E", "C"),
        component="A",
        layout_seed="L1",
        niche_affinity=("psychology", "law", "coaching"),
        mood="two-voice dialogue",
    ),
    "vault": CompositionConcept(
        id="vault",
        label="Vault of trust",
        section_order=(
            "trust",
            "process",
            "about",
            "mid_cta",
            "services",
            "gallery",
            "benefits",
            "showcase",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("C", "D", "A"),
        component="C",
        layout_seed="L2",
        niche_affinity=("law", "dental", "accounting", "psychology"),
        mood="credentials before offer",
    ),
    "runway": CompositionConcept(
        id="runway",
        label="Runway scroll",
        section_order=(
            "gallery",
            "showcase",
            "services",
            "mid_cta",
            "about",
            "stats",
            "trust",
            "process",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("B", "D", "F"),
        component="A",
        layout_seed="L4",
        niche_affinity=("fashion", "beauty", "photography"),
        mood="horizontal luxury feel",
    ),
    "hearth": CompositionConcept(
        id="hearth",
        label="Hearth & home",
        section_order=(
            "about",
            "gallery",
            "benefits",
            "mid_cta",
            "services",
            "trust",
            "process",
            "showcase",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("A", "C", "E"),
        component="A",
        layout_seed="L1",
        niche_affinity=("restaurant", "realestate", "green"),
        mood="warm belonging",
    ),
    "signal": CompositionConcept(
        id="signal",
        label="Signal strip",
        section_order=(
            "stats",
            "trust",
            "services",
            "mid_cta",
            "about",
            "gallery",
            "process",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("E", "A", "C"),
        component="B",
        layout_seed="L5",
        niche_affinity=("auto", "handwerk", "computer", "appliance"),
        mood="proof strip first",
    ),
    "atelier_night": CompositionConcept(
        id="atelier_night",
        label="Atelier night",
        section_order=(
            "showcase",
            "gallery",
            "about",
            "mid_cta",
            "services",
            "process",
            "trust",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "B", "F"),
        component="C",
        layout_seed="L6",
        niche_affinity=("beauty", "fashion", "photography", "psychology"),
        mood="dark atelier",
    ),
    "breath": CompositionConcept(
        id="breath",
        label="Breathing room",
        section_order=(
            "about",
            "mid_cta",
            "gallery",
            "services",
            "trust",
            "process",
            "benefits",
            "showcase",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("D", "C", "A"),
        component="C",
        layout_seed="L2",
        niche_affinity=("psychology", "dental", "green"),
        mood="maximum white-space intent — filled, not empty",
    ),
    "orbit": CompositionConcept(
        id="orbit",
        label="Orbit around offer",
        section_order=(
            "services",
            "gallery",
            "about",
            "mid_cta",
            "showcase",
            "trust",
            "process",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("E", "D", "A"),
        component="A",
        layout_seed="L3",
        niche_affinity=("beauty", "fitness", "restaurant"),
        mood="offer as center of gravity",
    ),
    "ledger": CompositionConcept(
        id="ledger",
        label="Ledger precision",
        section_order=(
            "about",
            "trust",
            "stats",
            "services",
            "mid_cta",
            "process",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("C", "A", "E"),
        component="B",
        layout_seed="L1",
        niche_affinity=("accounting", "law", "energy"),
        mood="precise ledger",
    ),
    "solstice": CompositionConcept(
        id="solstice",
        label="Solstice arc",
        section_order=(
            "gallery",
            "about",
            "mid_cta",
            "process",
            "services",
            "showcase",
            "trust",
            "benefits",
            "faq",
            "reviews",
            "maps",
            "late_cta",
            "contact",
        ),
        hero_layouts=("D", "B", "E"),
        component="A",
        layout_seed="L6",
        niche_affinity=("psychology", "green", "beauty"),
        mood="seasonal arc",
    ),
    "ember": CompositionConcept(
        id="ember",
        label="Ember warmth",
        section_order=(
            "about",
            "showcase",
            "benefits",
            "mid_cta",
            "services",
            "gallery",
            "trust",
            "process",
            "faq",
            "reviews",
            "maps",
            "contact",
        ),
        hero_layouts=("A", "D", "C"),
        component="A",
        layout_seed="L1",
        niche_affinity=("restaurant", "handwerk", "beauty"),
        mood="warm ember",
    ),
}


def list_compositions() -> list[CompositionConcept]:
    return list(COMPOSITION_LIBRARY.values())


def get_composition(composition_id: str) -> CompositionConcept | None:
    return COMPOSITION_LIBRARY.get((composition_id or "").strip().lower())


def compositions_for_niche(niche_id: str | None, *, premium: bool = True) -> list[CompositionConcept]:
    niche = (niche_id or "generic").strip().lower()
    scored: list[tuple[int, CompositionConcept]] = []
    for c in COMPOSITION_LIBRARY.values():
        score = 0
        if niche in c.niche_affinity:
            score += 10
        if premium and c.anti_predictable:
            score += 4
        if premium and not c.anti_predictable:
            score -= 6
        if niche == "psychology" and c.id in (
            "sanctuary",
            "garden",
            "whisper",
            "storytelling",
            "chamber",
            "cinematic",
            "magazine",
            "ritual",
            "horizon",
            "manifesto",
            "breath",
            "solstice",
            "floating",
            "narrative",
            "cascade",
            "spotlight",
            "nature",
            "atelier_night",
        ):
            score += 5
        scored.append((score, c))
    scored.sort(key=lambda x: (-x[0], x[1].id))
    return [c for _, c in scored]


def is_predictable_funnel(section_order: tuple[str, ...] | list[str]) -> bool:
    """True when the page reads as Hero → text/cards ladder."""
    keys = [k for k in section_order if k]
    if len(keys) < 4:
        return False
    head = tuple(keys[:5])
    for boring in _BORING_PREFIXES:
        if head[: len(boring)] == boring:
            return True
    # Three+ consecutive cardy blocks = section stack
    run = 0
    for k in keys:
        if k in CARDY_SECTIONS:
            run += 1
            if run >= 3:
                return True
        else:
            run = 0
    return False


def rhythm_signature(section_order: tuple[str, ...] | list[str]) -> str:
    """Compact signature for anti-clone / diversity."""
    return ">".join(section_order[:12])
