"""Export Virtus Core Website Auditor reports — JSON, CSV, Markdown, PDF."""

from __future__ import annotations

import csv
import io
import json
from typing import Any

from app.integration.vc_auditor.branding import PRODUCT_NAME


def export_json(report: dict[str, Any]) -> str:
    return json.dumps(report, ensure_ascii=False, indent=2)


def export_markdown(report: dict[str, Any]) -> str:
    overall = report.get("overall_business_score", 0)
    website = report.get("website") or {}
    legal = report.get("germany_legal") or {}
    business = report.get("business") or {}
    findings = report.get("findings") or []
    lines = [
        f"# {PRODUCT_NAME}",
        "",
        f"**Overall Business Score:** {overall} / 100",
        "",
        f"Mode: `{report.get('mode')}` · Target: `{report.get('target')}`",
        "",
        "## Website",
        "",
    ]
    for k, v in website.items():
        lines.append(f"- **{k.upper()}:** {v}")
    lines += ["", "## Germany Legal", ""]
    for row in legal.values() if isinstance(legal, dict) else []:
        mark = "✓" if row.get("pass") else "✗"
        lines.append(f"- {mark} {row.get('label')}")
    lines += ["", "## Business", ""]
    for row in business.values() if isinstance(business, dict) else []:
        mark = "✓" if row.get("pass") else "✗"
        lines.append(f"- {mark} {row.get('label')}")
    lines += ["", "## Findings", ""]
    if not findings:
        lines.append("_No open findings._")
    for f in findings:
        sev = str(f.get("severity") or "").upper()
        lines.append(f"- **[{sev}]** {f.get('message')}")
        act = f.get("action") or {}
        if act.get("kind") == "coming":
            lines.append(f"  - Coming {act.get('coming')}")
        elif act.get("label"):
            lines.append(f"  - Action: {act.get('label')}")
    lines += ["", "## AI Summary", "", str(report.get("ai_summary") or ""), ""]
    lines += [
        "---",
        f"Generated by {PRODUCT_NAME} · {report.get('engine_id')}",
        "",
    ]
    return "\n".join(lines)


def export_csv(report: dict[str, Any]) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["section", "id", "label", "score_or_status", "detail"])
    w.writerow(
        [
            "overall",
            "overall_business_score",
            "Overall Business Score",
            report.get("overall_business_score"),
            "",
        ]
    )
    for k, v in (report.get("website") or {}).items():
        w.writerow(["website", k, k.upper(), v, ""])
    for row in (report.get("germany_legal") or {}).values():
        w.writerow(
            [
                "germany_legal",
                row.get("id"),
                row.get("label"),
                "pass" if row.get("pass") else "fail",
                row.get("score"),
            ]
        )
    for row in (report.get("business") or {}).values():
        w.writerow(
            [
                "business",
                row.get("id"),
                row.get("label"),
                "pass" if row.get("pass") else "fail",
                row.get("score"),
            ]
        )
    for f in report.get("findings") or []:
        w.writerow(
            [
                "finding",
                f.get("id"),
                f.get("category"),
                f.get("severity"),
                f.get("message"),
            ]
        )
    w.writerow(["ai_summary", "ai_summary", "AI Summary", "", report.get("ai_summary")])
    return buf.getvalue()


def _pdf_escape(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace("(", "\\(")
        .replace(")", "\\)")
        .replace("\r", "")
    )


def export_pdf(report: dict[str, Any]) -> bytes:
    """Minimal multi-page-capable text PDF (no external deps)."""
    md = export_markdown(report)
    # PDF Latin-1 subset — replace unsupported chars
    lines: list[str] = []
    for raw in md.splitlines():
        safe = raw.encode("latin-1", errors="replace").decode("latin-1")
        # wrap long lines
        while len(safe) > 95:
            lines.append(safe[:95])
            safe = safe[95:]
        lines.append(safe)
    if not lines:
        lines = [PRODUCT_NAME]

    # Build content stream
    y_start = 800
    leading = 12
    max_lines_per_page = 60
    pages: list[list[str]] = []
    for i in range(0, len(lines), max_lines_per_page):
        pages.append(lines[i : i + max_lines_per_page])

    objects: list[bytes] = []
    # 1 catalog, 2 pages tree, then per page: page + content

    page_objs: list[int] = []
    content_objs: list[int] = []

    def add_obj(data: bytes) -> int:
        objects.append(data)
        return len(objects)

    # We'll assemble after knowing object numbers — simpler single-page if short
    # Multi-page: object 1=Catalog, 2=Pages, then pairs

    stream_ids: list[int] = []
    page_ids: list[int] = []

    # Reserve: we'll build in order
    # obj1 Catalog -> Pages
    # obj2 Pages
    # for each page: content stream, page dict

    content_buffers: list[bytes] = []
    for page_lines in pages:
        parts = ["BT", "/F1 10 Tf", "50 800 Td", f"{leading} TL"]
        first = True
        for line in page_lines:
            esc = _pdf_escape(line)
            if first:
                parts.append(f"({esc}) Tj")
                first = False
            else:
                parts.append("T*")
                parts.append(f"({esc}) Tj")
        parts.append("ET")
        stream = "\n".join(parts).encode("latin-1", errors="replace")
        content_buffers.append(stream)

    # Object layout:
    # 1: Catalog
    # 2: Pages
    # 3: Font
    # then for i, page:  content (4+2i), page (5+2i)
    font_id = 3
    objs: dict[int, bytes] = {}
    objs[font_id] = b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"

    kids = []
    next_id = 4
    for stream in content_buffers:
        cid = next_id
        next_id += 1
        pid = next_id
        next_id += 1
        objs[cid] = (
            f"<< /Length {len(stream)} >>\nstream\n".encode("ascii")
            + stream
            + b"\nendstream"
        )
        objs[pid] = (
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            f"/Contents {cid} 0 R /Resources << /Font << /F1 {font_id} 0 R >> >> >>"
        ).encode("ascii")
        kids.append(f"{pid} 0 R")

    kids_str = " ".join(kids)
    objs[2] = (
        f"<< /Type /Pages /Kids [{kids_str}] /Count {len(kids)} >>"
    ).encode("ascii")
    objs[1] = b"<< /Type /Catalog /Pages 2 0 R >>"

    # Serialize PDF
    out = bytearray(b"%PDF-1.4\n")
    offsets = {0: 0}
    max_id = max(objs)
    for i in range(1, max_id + 1):
        offsets[i] = len(out)
        out.extend(f"{i} 0 obj\n".encode("ascii"))
        out.extend(objs[i])
        out.extend(b"\nendobj\n")

    xref_pos = len(out)
    out.extend(f"xref\n0 {max_id + 1}\n".encode("ascii"))
    out.extend(b"0000000000 65535 f \n")
    for i in range(1, max_id + 1):
        out.extend(f"{offsets[i]:010d} 00000 n \n".encode("ascii"))
    out.extend(
        f"trailer\n<< /Size {max_id + 1} /Root 1 0 R >>\nstartxref\n{xref_pos}\n%%EOF\n".encode(
            "ascii"
        )
    )
    return bytes(out)


def export_report(report: dict[str, Any], fmt: str) -> tuple[bytes, str, str]:
    """Return (body, media_type, filename_suffix)."""
    fmt = (fmt or "json").lower().strip()
    if fmt in ("md", "markdown"):
        return (
            export_markdown(report).encode("utf-8"),
            "text/markdown; charset=utf-8",
            "md",
        )
    if fmt == "csv":
        return (
            export_csv(report).encode("utf-8"),
            "text/csv; charset=utf-8",
            "csv",
        )
    if fmt == "pdf":
        return export_pdf(report), "application/pdf", "pdf"
    return (
        export_json(report).encode("utf-8"),
        "application/json; charset=utf-8",
        "json",
    )
