"""Niche design profiles for Path A Factory landings.

Gate 1: in-code profiles (niche_id → full design system). Horizon: load
factory/themes/{niche_id}/config.json without changing build_landing call shape —
only resolve_niche_profile() grows.

R2.1 / Website Factory: niches are not color swaps — typography, radii, surfaces
differ so dental vs auto vs law vs restaurant read as different agency products.

Font stacks are also resolved via Design Engine font packs (Google Fonts + fallback).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class NicheStyle:
    primary: str
    primary_dark: str
    accent: str
    hero_gradient: str
    ink: str = "#0f172a"
    muted: str = "#64748b"
    surface: str = "#f8fafc"
    line: str = "#e2e8f0"
    font_body: str = '"DM Sans", "Segoe UI", system-ui, -apple-system, sans-serif'
    font_display: str = '"DM Sans", "Segoe UI", system-ui, -apple-system, sans-serif'
    radius: str = "12px"
    btn_radius: str = "999px"
    card_radius: str = "12px"
    shadow: str = "0 12px 24px rgba(0,0,0,0.08)"
    letter_spacing: str = "-0.02em"
    btn_weight: str = "700"


@dataclass(frozen=True)
class NicheProfile:
    niche_id: str
    label_de: str
    style: NicheStyle


# Path A industry systems — fonts/radii/surfaces are part of identity, not optional.
_PROFILES: dict[str, NicheProfile] = {
    "auto": NicheProfile(
        "auto",
        "Autowerkstatt",
        NicheStyle(
            primary="#b91c1c",
            primary_dark="#7f1d1d",
            accent="#f87171",
            hero_gradient="linear-gradient(135deg,#0a0a0a 0%,#1c1917 45%,#b91c1c 100%)",
            ink="#0c0a09",
            muted="#78716c",
            surface="#f5f5f4",
            line="#e7e5e4",
            font_body='"DM Sans", "Helvetica Neue", Arial, sans-serif',
            font_display='"Barlow Condensed", "Arial Narrow", Impact, sans-serif',
            radius="6px",
            btn_radius="6px",
            card_radius="8px",
            shadow="0 16px 32px rgba(0,0,0,0.14)",
            letter_spacing="-0.03em",
            btn_weight="800",
        ),
    ),
    "dental": NicheProfile(
        "dental",
        "Zahnmedizin",
        NicheStyle(
            primary="#0284c7",
            primary_dark="#0369a1",
            accent="#e0f2fe",
            hero_gradient="linear-gradient(135deg,#0369a1 0%,#0ea5e9 55%,#38bdf8 100%)",
            ink="#0c4a6e",
            muted="#64748b",
            surface="#f0f9ff",
            line="#bae6fd",
            font_body='"DM Sans", system-ui, -apple-system, sans-serif',
            font_display='"DM Sans", system-ui, -apple-system, sans-serif',
            radius="16px",
            btn_radius="999px",
            card_radius="18px",
            shadow="0 10px 28px rgba(3,105,161,0.10)",
            letter_spacing="-0.02em",
            btn_weight="700",
        ),
    ),
    "law": NicheProfile(
        "law",
        "Kanzlei",
        NicheStyle(
            primary="#1e3a5f",
            primary_dark="#0f172a",
            accent="#c9a227",
            hero_gradient="linear-gradient(135deg,#0f172a 0%,#1e3a5f 70%,#334155 100%)",
            ink="#0f172a",
            muted="#64748b",
            surface="#f8fafc",
            line="#e2e8f0",
            font_body='"Source Sans 3", Calibri, system-ui, sans-serif',
            font_display='"Libre Baskerville", Georgia, "Times New Roman", serif',
            radius="4px",
            btn_radius="4px",
            card_radius="6px",
            shadow="0 8px 20px rgba(15,23,42,0.08)",
            letter_spacing="0.01em",
            btn_weight="600",
        ),
    ),
    "beauty": NicheProfile(
        "beauty",
        "Salon",
        NicheStyle(
            primary="#be185d",
            primary_dark="#9d174d",
            accent="#fbcfe8",
            hero_gradient="linear-gradient(150deg,#831843 0%,#be185d 50%,#db2777 100%)",
            ink="#500724",
            muted="#9d174d",
            surface="#fdf2f8",
            line="#fbcfe8",
            font_body='"DM Sans", "Helvetica Neue", system-ui, sans-serif',
            font_display='"Cormorant Garamond", Georgia, Palatino, serif',
            radius="14px",
            btn_radius="999px",
            card_radius="16px",
            shadow="0 14px 36px rgba(190,24,93,0.12)",
            letter_spacing="0.02em",
            btn_weight="600",
        ),
    ),
    "fashion": NicheProfile(
        "fashion",
        "Mode / Boutique",
        NicheStyle(
            primary="#e11d48",
            primary_dark="#9f1239",
            accent="#fb7185",
            hero_gradient="linear-gradient(145deg,#0a0a0a 0%,#1c1917 40%,#881337 100%)",
            ink="#0c0a09",
            muted="#a8a29e",
            surface="#0c0a09",
            line="#292524",
            font_body='"DM Sans", "Helvetica Neue", Arial, sans-serif',
            font_display='"Cormorant Garamond", Georgia, "Times New Roman", serif',
            radius="2px",
            btn_radius="999px",
            card_radius="4px",
            shadow="0 24px 48px rgba(0,0,0,0.45)",
            letter_spacing="0.04em",
            btn_weight="600",
        ),
    ),
    "energy": NicheProfile(
        "energy",
        "Photovoltaik",
        NicheStyle(
            primary="#16a34a",
            primary_dark="#15803d",
            accent="#facc15",
            hero_gradient="linear-gradient(135deg,#14532d 0%,#16a34a 50%,#ca8a04 100%)",
            ink="#14532d",
            muted="#4d7c0f",
            surface="#f7fee7",
            line="#d9f99d",
            font_body='"DM Sans", system-ui, -apple-system, sans-serif',
            font_display='"DM Sans", system-ui, -apple-system, sans-serif',
            radius="18px",
            btn_radius="14px",
            card_radius="20px",
            shadow="0 12px 30px rgba(22,163,74,0.12)",
            letter_spacing="-0.01em",
            btn_weight="700",
        ),
    ),
    "restaurant": NicheProfile(
        "restaurant",
        "Restaurant / Gastronomie",
        NicheStyle(
            primary="#c2410c",
            primary_dark="#7c2d12",
            accent="#fdba74",
            hero_gradient="linear-gradient(155deg,#1c1917 0%,#7c2d12 48%,#c2410c 100%)",
            ink="#1c1917",
            muted="#78716c",
            surface="#faf6f1",
            line="#e7e0d5",
            font_body='"DM Sans", "Segoe UI", system-ui, sans-serif',
            font_display='"Fraunces", Georgia, "Times New Roman", serif',
            radius="10px",
            btn_radius="999px",
            card_radius="14px",
            shadow="0 18px 40px rgba(124,45,18,0.12)",
            letter_spacing="0.01em",
            btn_weight="600",
        ),
    ),
    "handwerk": NicheProfile(
        "handwerk",
        "Handwerk",
        NicheStyle(
            primary="#b45309",
            primary_dark="#78350f",
            accent="#fbbf24",
            hero_gradient="linear-gradient(135deg,#1c1917 0%,#44403c 40%,#b45309 100%)",
            ink="#1c1917",
            muted="#78716c",
            surface="#fafaf9",
            line="#e7e5e4",
            font_body='"Source Sans 3", "Segoe UI", system-ui, sans-serif',
            font_display='"Oswald", "Arial Narrow", Impact, sans-serif',
            radius="4px",
            btn_radius="4px",
            card_radius="6px",
            shadow="0 14px 28px rgba(28,25,23,0.12)",
            letter_spacing="0.02em",
            btn_weight="700",
        ),
    ),
    "dachreinigung": NicheProfile(
        "dachreinigung",
        "Dachreinigung",
        NicheStyle(
            primary="#3b82c4",
            primary_dark="#1e3a5f",
            accent="#93c5e8",
            hero_gradient="linear-gradient(145deg,#0f1720 0%,#1e293b 45%,#3b82c4 100%)",
            ink="#0f172a",
            muted="#64748b",
            surface="#f1f5f9",
            line="#cbd5e1",
            font_body='"Source Sans 3", "Segoe UI", system-ui, sans-serif',
            font_display='"Oswald", "Arial Narrow", Impact, sans-serif',
            radius="6px",
            btn_radius="6px",
            card_radius="8px",
            shadow="0 16px 32px rgba(15,23,42,0.14)",
            letter_spacing="0.03em",
            btn_weight="700",
        ),
    ),
    "zaunbau": NicheProfile(
        "zaunbau",
        "Zaunbau",
        NicheStyle(
            primary="#92400e",
            primary_dark="#451a03",
            accent="#d97706",
            hero_gradient="linear-gradient(135deg,#1c1410 0%,#44403c 40%,#92400e 100%)",
            ink="#1c1917",
            muted="#78716c",
            surface="#faf7f2",
            line="#e7e5e4",
            font_body='"Source Sans 3", "Segoe UI", system-ui, sans-serif',
            font_display='"Roboto Slab", Georgia, serif',
            radius="4px",
            btn_radius="4px",
            card_radius="6px",
            shadow="0 14px 28px rgba(28,25,23,0.12)",
            letter_spacing="0.01em",
            btn_weight="700",
        ),
    ),
    "gartenpflege": NicheProfile(
        "gartenpflege",
        "Gartenpflege",
        NicheStyle(
            primary="#15803d",
            primary_dark="#14532d",
            accent="#86efac",
            hero_gradient="linear-gradient(145deg,#0a1f12 0%,#14532d 50%,#22c55e 100%)",
            ink="#14532d",
            muted="#4d7c0f",
            surface="#f0fdf4",
            line="#bbf7d0",
            font_body='"Source Sans 3", "Segoe UI", system-ui, sans-serif',
            font_display='"Fraunces", Georgia, serif',
            radius="14px",
            btn_radius="999px",
            card_radius="16px",
            shadow="0 16px 36px rgba(20,83,45,0.12)",
            letter_spacing="0.01em",
            btn_weight="600",
        ),
    ),
    "green": NicheProfile(
        "green",
        "Garten",
        NicheStyle(
            primary="#22c55e",
            primary_dark="#166534",
            accent="#86efac",
            hero_gradient="linear-gradient(135deg,#14532d,#22c55e)",
            ink="#14532d",
            muted="#4d7c0f",
            surface="#f0fdf4",
            line="#bbf7d0",
            font_body='"DM Sans", system-ui, sans-serif',
            font_display='"DM Sans", system-ui, sans-serif',
            radius="14px",
            btn_radius="12px",
            card_radius="16px",
            shadow="0 12px 28px rgba(22,163,74,0.10)",
            letter_spacing="-0.01em",
            btn_weight="700",
        ),
    ),
    "computer": NicheProfile(
        "computer",
        "PC-Service",
        NicheStyle(
            primary="#0369a1",
            primary_dark="#0c4a6e",
            accent="#38bdf8",
            hero_gradient="linear-gradient(135deg,#0f172a,#0284c7)",
            ink="#0f172a",
            muted="#64748b",
            surface="#f1f5f9",
            line="#cbd5e1",
            font_body='"DM Sans", system-ui, sans-serif',
            font_display='"DM Sans", system-ui, sans-serif',
            radius="10px",
            btn_radius="8px",
            card_radius="12px",
            shadow="0 10px 24px rgba(3,105,161,0.10)",
            letter_spacing="-0.02em",
            btn_weight="700",
        ),
    ),
    "appliance": NicheProfile(
        "appliance",
        "Hausgeräte",
        NicheStyle(
            primary="#475569",
            primary_dark="#1e293b",
            accent="#94a3b8",
            hero_gradient="linear-gradient(135deg,#0f172a,#475569)",
            ink="#0f172a",
            muted="#64748b",
            surface="#f8fafc",
            line="#e2e8f0",
            font_body='"DM Sans", system-ui, sans-serif',
            font_display='"DM Sans", system-ui, sans-serif',
            radius="8px",
            btn_radius="8px",
            card_radius="10px",
            shadow="0 10px 22px rgba(15,23,42,0.08)",
            letter_spacing="-0.015em",
            btn_weight="700",
        ),
    ),
    "cleaning": NicheProfile(
        "cleaning",
        "Reinigung",
        NicheStyle(
            primary="#0e7490",
            primary_dark="#155e75",
            accent="#67e8f9",
            hero_gradient="linear-gradient(135deg,#083344,#0e7490)",
            ink="#083344",
            muted="#0e7490",
            surface="#ecfeff",
            line="#a5f3fc",
            font_body='"DM Sans", system-ui, sans-serif',
            font_display='"DM Sans", system-ui, sans-serif',
            radius="12px",
            btn_radius="999px",
            card_radius="14px",
            shadow="0 12px 26px rgba(14,116,144,0.10)",
            letter_spacing="-0.01em",
            btn_weight="700",
        ),
    ),
    "auto_ankauf": NicheProfile(
        "auto_ankauf",
        "Autoankauf",
        NicheStyle(
            primary="#b91c1c",
            primary_dark="#7f1d1d",
            accent="#fbbf24",
            hero_gradient="linear-gradient(135deg,#0a0a0a 0%,#1c1917 45%,#b91c1c 100%)",
            ink="#0c0a09",
            muted="#78716c",
            surface="#f5f5f4",
            line="#e7e5e4",
            font_body='"DM Sans", "Helvetica Neue", Arial, sans-serif',
            font_display='"Barlow Condensed", "Arial Narrow", Impact, sans-serif',
            radius="6px",
            btn_radius="6px",
            card_radius="8px",
            shadow="0 16px 32px rgba(0,0,0,0.14)",
            letter_spacing="-0.03em",
            btn_weight="800",
        ),
    ),
    "accounting": NicheProfile(
        "accounting",
        "Steuerberatung",
        NicheStyle(
            primary="#0f766e",
            primary_dark="#115e59",
            accent="#99f6e4",
            hero_gradient="linear-gradient(135deg,#134e4a,#0f766e)",
            ink="#134e4a",
            muted="#0f766e",
            surface="#f0fdfa",
            line="#99f6e4",
            font_body='"Source Sans 3", "Segoe UI", system-ui, sans-serif',
            font_display='"Source Serif 4", Georgia, serif',
            radius="6px",
            btn_radius="6px",
            card_radius="8px",
            shadow="0 10px 24px rgba(15,118,110,0.10)",
            letter_spacing="0em",
            btn_weight="600",
        ),
    ),
    "photography": NicheProfile(
        "photography",
        "Fotografie",
        NicheStyle(
            primary="#18181b",
            primary_dark="#09090b",
            accent="#a1a1aa",
            hero_gradient="linear-gradient(135deg,#09090b 0%,#27272a 55%,#52525b 100%)",
            ink="#18181b",
            muted="#71717a",
            surface="#fafafa",
            line="#e4e4e7",
            font_body='"DM Sans", "Segoe UI", system-ui, sans-serif',
            font_display='"Source Serif 4", Georgia, "Times New Roman", serif',
            radius="4px",
            btn_radius="4px",
            card_radius="8px",
            shadow="0 16px 36px rgba(0,0,0,0.12)",
            letter_spacing="0.02em",
            btn_weight="600",
        ),
    ),
    "fitness": NicheProfile(
        "fitness",
        "Fitness",
        NicheStyle(
            primary="#ea580c",
            primary_dark="#9a3412",
            accent="#fdba74",
            hero_gradient="linear-gradient(135deg,#1c1917,#ea580c)",
            ink="#1c1917",
            muted="#9a3412",
            surface="#fff7ed",
            line="#fed7aa",
            font_body='"DM Sans", system-ui, sans-serif',
            font_display='"Oswald", "Arial Narrow", sans-serif',
            radius="8px",
            btn_radius="6px",
            card_radius="10px",
            shadow="0 14px 30px rgba(234,88,12,0.12)",
            letter_spacing="0.03em",
            btn_weight="800",
        ),
    ),
    "orthodontics": NicheProfile(
        "orthodontics",
        "Kieferorthopädie",
        NicheStyle(
            primary="#0d9488",
            primary_dark="#115e59",
            accent="#5eead4",
            hero_gradient="linear-gradient(135deg,#042f2e,#0d9488)",
            ink="#134e4a",
            muted="#0f766e",
            surface="#f0fdfa",
            line="#99f6e4",
            font_body='"DM Sans", system-ui, sans-serif',
            font_display='"Fraunces", Georgia, serif',
            radius="14px",
            btn_radius="999px",
            card_radius="16px",
            shadow="0 14px 28px rgba(13,148,136,0.12)",
            letter_spacing="-0.02em",
            btn_weight="700",
        ),
    ),
    "auto_detailing": NicheProfile(
        "auto_detailing",
        "Fahrzeugdetailing",
        NicheStyle(
            primary="#0a0a0a",
            primary_dark="#000000",
            accent="#d4af37",
            hero_gradient="linear-gradient(145deg,#050505 0%,#1a1a1a 50%,#3f3f46 100%)",
            ink="#fafafa",
            muted="#a1a1aa",
            surface="#18181b",
            line="#27272a",
            font_body='"Inter", "Segoe UI", sans-serif',
            font_display='"Orbitron", "Arial Narrow", sans-serif',
            radius="4px",
            btn_radius="4px",
            card_radius="8px",
            shadow="0 20px 40px rgba(0,0,0,0.45)",
            letter_spacing="0.04em",
            btn_weight="800",
        ),
    ),
    "it_support": NicheProfile(
        "it_support",
        "IT-Support",
        NicheStyle(
            primary="#1d4ed8",
            primary_dark="#1e3a8a",
            accent="#22d3ee",
            hero_gradient="linear-gradient(135deg,#0f172a,#1d4ed8)",
            ink="#0f172a",
            muted="#334155",
            surface="#f8fafc",
            line="#e2e8f0",
            font_body='"IBM Plex Sans", "Segoe UI", sans-serif',
            font_display='"IBM Plex Sans", "Segoe UI", sans-serif',
            radius="10px",
            btn_radius="8px",
            card_radius="12px",
            shadow="0 12px 28px rgba(29,78,216,0.12)",
            letter_spacing="-0.03em",
            btn_weight="700",
        ),
    ),
    "realestate": NicheProfile(
        "realestate",
        "Immobilien",
        NicheStyle(
            primary="#1d4ed8",
            primary_dark="#1e3a8a",
            accent="#93c5fd",
            hero_gradient="linear-gradient(135deg,#0f172a,#1d4ed8)",
            ink="#0f172a",
            muted="#475569",
            surface="#f8fafc",
            line="#bfdbfe",
            font_body='"Source Sans 3", "Segoe UI", system-ui, sans-serif',
            font_display='"Libre Baskerville", Georgia, serif',
            radius="8px",
            btn_radius="6px",
            card_radius="10px",
            shadow="0 12px 28px rgba(29,78,216,0.10)",
            letter_spacing="0em",
            btn_weight="600",
        ),
    ),
    "psychology": NicheProfile(
        "psychology",
        "Psychologie",
        NicheStyle(
            # Calm Clinical — soft sage / warm sand, never dental cyan or beauty pink
            primary="#5b7c6e",
            primary_dark="#3f5a4f",
            accent="#c9b8a6",
            hero_gradient="linear-gradient(145deg,#f7f4ef 0%,#e8efe9 48%,#d4e0d8 100%)",
            ink="#2c3330",
            muted="#6b736e",
            surface="#fbf9f6",
            line="#e4ebe6",
            font_body='"Source Sans 3", "Segoe UI", system-ui, sans-serif',
            font_display='"Cormorant Garamond", Georgia, "Times New Roman", serif',
            radius="18px",
            btn_radius="999px",
            card_radius="20px",
            shadow="0 14px 36px rgba(63,90,79,0.08)",
            letter_spacing="0.01em",
            btn_weight="600",
        ),
    ),

    "elektro": NicheProfile(
        "elektro",
        "Elektro",
        NicheStyle(
            primary="#ca8a04",
            primary_dark="#713f12",
            accent="#facc15",
            hero_gradient="linear-gradient(135deg,#0c0a09 0%,#292524 42%,#ca8a04 100%)",
            ink="#1c1917",
            muted="#78716c",
            surface="#fafaf9",
            line="#e7e5e4",
            font_body='"Source Sans 3", "Segoe UI", system-ui, sans-serif',
            font_display='"Oswald", "Arial Narrow", Impact, sans-serif',
            radius="4px",
            btn_radius="4px",
            card_radius="6px",
            shadow="0 14px 28px rgba(28,25,23,0.12)",
            letter_spacing="0.02em",
            btn_weight="700",
        ),
    ),
    "sanitaer": NicheProfile(
        "sanitaer",
        "Sanitär",
        NicheStyle(
            primary="#0369a1",
            primary_dark="#0c4a6e",
            accent="#38bdf8",
            hero_gradient="linear-gradient(135deg,#0c4a6e 0%,#164e63 45%,#0369a1 100%)",
            ink="#0f172a",
            muted="#64748b",
            surface="#f8fafc",
            line="#e2e8f0",
            font_body='"Source Sans 3", "Segoe UI", system-ui, sans-serif',
            font_display='"Oswald", "Arial Narrow", Impact, sans-serif',
            radius="6px",
            btn_radius="6px",
            card_radius="8px",
            shadow="0 14px 28px rgba(12,74,110,0.12)",
            letter_spacing="0.02em",
            btn_weight="700",
        ),
    ),
    "maler": NicheProfile(
        "maler",
        "Maler",
        NicheStyle(
            primary="#c2410c",
            primary_dark="#7c2d12",
            accent="#fdba74",
            hero_gradient="linear-gradient(135deg,#1c1917 0%,#44403c 40%,#c2410c 100%)",
            ink="#1c1917",
            muted="#78716c",
            surface="#fafaf9",
            line="#e7e5e4",
            font_body='"Source Sans 3", "Segoe UI", system-ui, sans-serif',
            font_display='"Oswald", "Arial Narrow", Impact, sans-serif',
            radius="4px",
            btn_radius="4px",
            card_radius="6px",
            shadow="0 14px 28px rgba(28,25,23,0.12)",
            letter_spacing="0.02em",
            btn_weight="700",
        ),
    ),
    "family_psychology": NicheProfile(
        "family_psychology",
        "Familienpsychologie",
        NicheStyle(
            primary="#6b8f7a",
            primary_dark="#4a6b58",
            accent="#d4a574",
            hero_gradient="linear-gradient(145deg,#faf6f1 0%,#efe8df 48%,#dce8e0 100%)",
            ink="#2c3330",
            muted="#6b736e",
            surface="#fbf9f6",
            line="#e8ebe4",
            font_body='"Source Sans 3", "Segoe UI", system-ui, sans-serif',
            font_display='"Cormorant Garamond", Georgia, "Times New Roman", serif',
            radius="18px",
            btn_radius="999px",
            card_radius="20px",
            shadow="0 14px 36px rgba(74,107,88,0.08)",
            letter_spacing="0.01em",
            btn_weight="600",
        ),
    ),
    "car_dealership": NicheProfile(
        "car_dealership",
        "Autohaus",
        NicheStyle(
            primary="#1e293b",
            primary_dark="#020617",
            accent="#94a3b8",
            hero_gradient="linear-gradient(135deg,#020617 0%,#0f172a 45%,#334155 100%)",
            ink="#0c0a09",
            muted="#64748b",
            surface="#f1f5f9",
            line="#e2e8f0",
            font_body='"DM Sans", "Helvetica Neue", Arial, sans-serif',
            font_display='"Barlow Condensed", "Arial Narrow", Impact, sans-serif',
            radius="6px",
            btn_radius="6px",
            card_radius="8px",
            shadow="0 16px 32px rgba(0,0,0,0.18)",
            letter_spacing="-0.03em",
            btn_weight="800",
        ),
    ),
    "generic": NicheProfile(
        "generic",
        "Lokalgeschäft",
        NicheStyle(
            primary="#334155",
            primary_dark="#0f172a",
            accent="#38bdf8",
            hero_gradient="linear-gradient(135deg,#0f172a,#334155)",
            ink="#0f172a",
            muted="#64748b",
            surface="#f8fafc",
            line="#e2e8f0",
            font_body='"DM Sans", system-ui, sans-serif',
            font_display='"DM Sans", system-ui, sans-serif',
            radius="12px",
            btn_radius="999px",
            card_radius="12px",
            shadow="0 12px 24px rgba(0,0,0,0.08)",
            letter_spacing="-0.02em",
            btn_weight="700",
        ),
    ),
}


def resolve_niche_profile(niche_id: str | None) -> NicheProfile:
    """Extension point for tomorrow: niche_id from order / site analysis → profile."""
    key = (niche_id or "generic").strip().lower() or "generic"
    return _PROFILES.get(key, _PROFILES["generic"])


def known_niche_ids() -> tuple[str, ...]:
    return tuple(sorted(_PROFILES.keys()))


def niche_style_extra_css(profile: NicheProfile) -> str:
    """CSS overrides via Design Engine so each niche reads as its own system."""
    from app.factory.design_engine import emit_css_vars, resolve_for_niche

    return emit_css_vars(resolve_for_niche(profile.niche_id))
