"""Restore classic /vitrine cards in AppStoreHub."""
from pathlib import Path

path = Path("dashboard/frontend/app/components/storefront/AppStoreHub.tsx")
text = path.read_text(encoding="utf-8")
start = text.index("  const exampleProjects = [")
end = text.index("  return (", start)
new = r'''  const exampleProjects = [
    {
      id: "beauty-lumia",
      emoji: "💅",
      labelKey: "examples.beautyLumia",
      fallback: "Studio LUMIA · Nail, Brow, Lash & Massage",
      blurb: "Maniküre, Augenbrauen, Wimpern, Massage — Atelier München",
      thumb: "/vitrine/web-lumia.jpg",
      href: "/package-previews/sites/premium/beauty/index.html",
      kind: "website" as const,
      price: "Website · ab 199 €",
    },
    {
      id: "beauty-store-lumia",
      emoji: "🧴",
      labelKey: "examples.beautyStoreLumia",
      fallback: "LUMIA Care Shop · Beauty products",
      blurb: "Öle, Pflege, Profi-Kosmetik — Fortsetzung der Marke",
      thumb: "/vitrine/store-lumia.jpg",
      href: "/package-previews/stores/premium/beauty/catalog.html",
      kind: "store" as const,
      price: "AI Store · ab 799 €",
    },
    {
      id: "cleaning",
      emoji: "🧹",
      labelKey: "examples.cleaning",
      fallback: "Reinigung · Cleaning Company",
      blurb: "Privat & Gewerbe — pünktlich, sichtbar sauber",
      thumb: "/vitrine/web-cleaning.jpg",
      href: "/package-previews/sites/premium/cleaning/index.html",
      kind: "website" as const,
      price: "Website · ab 199 €",
    },
    {
      id: "cleaning-store",
      emoji: "🧼",
      labelKey: "examples.cleaningStore",
      fallback: "Reinigung · Online-Shop",
      blurb: "Reinigungsmittel, Bundles, Nachbestellung",
      thumb: "/vitrine/store-cleaning.jpg",
      href: "/package-previews/stores/premium/cleaning_shop/catalog.html",
      kind: "store" as const,
      price: "AI Store · ab 799 €",
    },
    {
      id: "it",
      emoji: "💻",
      labelKey: "examples.it",
      fallback: "Computer-Reparatur & Diagnose",
      blurb: "Diagnose, Reparatur, Datenrettung, Vor-Ort",
      thumb: "/vitrine/web-it.jpg",
      href: "/package-previews/sites/premium/it_support/index.html",
      kind: "website" as const,
      price: "Website · ab 199 €",
    },
    {
      id: "electronics-store",
      emoji: "🔌",
      labelKey: "examples.electronicsStore",
      fallback: "Elektronik · Online-Shop",
      blurb: "Geräte, Zubehör, Specs, Versand",
      thumb: "/vitrine/store-electronics.jpg",
      href: "/package-previews/stores/premium/electronics/catalog.html",
      kind: "store" as const,
      price: "AI Store · ab 799 €",
    },
    {
      id: "dental",
      emoji: "🦷",
      labelKey: "examples.dental",
      fallback: "Zahnarztpraxis",
      blurb: "Moderne Zahnmedizin, Vorsorge, Termin",
      thumb: "/vitrine/web-dental.jpg",
      href: "/package-previews/sites/premium/dental/index.html",
      kind: "website" as const,
      price: "Website · ab 199 €",
    },
    {
      id: "restaurant",
      emoji: "🍽",
      labelKey: "examples.restaurant",
      fallback: "Restaurant",
      blurb: "Menü, Reservierung, Atmosphäre",
      thumb: "/vitrine/web-restaurant.jpg",
      href: "/package-previews/sites/premium/restaurant/index.html",
      kind: "website" as const,
      price: "Website · ab 199 €",
    },
    {
      id: "food-store",
      emoji: "🛒",
      labelKey: "examples.foodStore",
      fallback: "Food & Feinkost · Online-Shop",
      blurb: "Spezialitäten, Sets, Lieferung",
      thumb: "/vitrine/store-food.jpg",
      href: "/package-previews/stores/premium/food/catalog.html",
      kind: "store" as const,
      price: "AI Store · ab 799 €",
    },
    {
      id: "handwerk",
      emoji: "🔨",
      labelKey: "examples.handwerk",
      fallback: "Handwerk & Renovierung",
      blurb: "Meister vor Ort — Projekte, Team, Festpreis",
      thumb: "/vitrine/web-handwerk.jpg",
      href: "/package-previews/sites/premium/handwerk/index.html",
      kind: "website" as const,
      price: "Website · ab 199 €",
    },
    {
      id: "furniture-store",
      emoji: "🪑",
      labelKey: "examples.furnitureStore",
      fallback: "Möbel · Online-Shop",
      blurb: "Räume, Katalog, Checkout",
      thumb: "/vitrine/store-furniture.jpg",
      href: "/package-previews/stores/premium/furniture/catalog.html",
      kind: "store" as const,
      price: "AI Store · ab 799 €",
    },
    {
      id: "law",
      emoji: "⚖️",
      labelKey: "examples.law",
      fallback: "Rechtsanwalt",
      blurb: "Bereiche, Team, Erstgespräch",
      thumb: "/vitrine/web-law.jpg",
      href: "/package-previews/sites/premium/law/index.html",
      kind: "website" as const,
      price: "Website · ab 199 €",
    },
    {
      id: "auto",
      emoji: "🔧",
      labelKey: "examples.auto",
      fallback: "Autowerkstatt",
      blurb: "Diagnose, Inspektion, Bremsen, TÜV — Premium + 3D",
      thumb: "/vitrine/web-auto.jpg",
      href: "/package-previews/sites/premium/auto/index.html",
      kind: "website" as const,
      price: "Website · ab 199 €",
    },
    {
      id: "fashion-store",
      emoji: "👗",
      labelKey: "examples.fashionStore",
      fallback: "Fashion · Online-Shop",
      blurb: "Looks, Kollektionen, Warenkorb, Admin",
      thumb: "/vitrine/store-fashion.jpg",
      href: "/package-previews/stores/premium/fashion/catalog.html",
      kind: "store" as const,
      price: "AI Store · ab 799 €",
    },
    {
      id: "beauty-store",
      emoji: "✨",
      labelKey: "examples.beautyStore",
      fallback: "Beauty · Online-Shop",
      blurb: "Pflege, Bundles, Reviews",
      thumb: "/vitrine/store-beauty.jpg",
      href: "/package-previews/stores/premium/beauty/catalog.html",
      kind: "store" as const,
      price: "AI Store · ab 799 €",
    },
  ];

'''
path.write_text(text[:start] + new + text[end:], encoding="utf-8")
print("ok", start, end)
