# Patch website package marketing copy in de/en/ru site.json (appStore.pricing + diffBasic*).
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "dashboard" / "frontend" / "locales"

PATCH: dict[str, dict[str, str]] = {
    "de": {
        "diffBasic1": "199 €: modernes responsives Website — Landing oder kompakter Auftritt",
        "diffBasic2": "Kontaktformular, Impressum, Datenschutz, Basis-SEO, Maps & Chat",
        "diffBasic3": "Schneller Online-Gang — ohne Admin-Panel; Business/Premium = mehr Visual & CMS",
        "webBasic": "Website Starter",
        "webBasicBlurb": "199 € einmalig — modernes responsives Website für den schnellen Start. Ideal für KMU, Freiberufler und die erste Online-Präsenz.",
        "webBusiness": "Business Website",
        "webBusinessBlurb": "399 € einmalig — vollwertige Website mit Admin-Panel. Texte und Bilder selbst ändern — plus Business Visual Pack.",
        "webPremium": "Premium Website",
        "webPremiumBlurb": "699 € einmalig — maximale Version: Premium Design & Motion, SEO Pro, AI Vector, Rollen und Prioritäts-Support.",
        "webBasicF1": "Modernes Design",
        "webBasicF2": "Responsive (Handy & Tablet)",
        "webBasicF3": "Kontaktformular",
        "webBasicF4": "Google Maps",
        "webBasicF5": "WhatsApp / Telegram / Social",
        "webBasicF6": "Impressum & Datenschutz",
        "webBasicF7": "Basis-SEO",
        "webBasicF8": "Schnelle Ladezeit",
        "webBasicF9": "Landing oder kompakter Firmenauftritt",
        "webBasicF10": "Ohne Admin-Panel",
        "webBusinessF1": "Alles aus Starter",
        "webBusinessF2": "Admin-Panel",
        "webBusinessF3": "Seiten bearbeiten",
        "webBusinessF4": "Bilder hochladen",
        "webBusinessF5": "Blog / News",
        "webBusinessF6": "Analytics",
        "webBusinessF7": "Content-Verwaltung",
        "webBusinessF8": "Kontaktformulare",
        "webBusinessF9": "Ein- oder mehrseitig — je nach Projekt",
        "webBusinessF10": "Business Visual Pack (Hero, Motion, Assets)",
        "webPremiumF1": "Alles aus Business",
        "webPremiumF2": "Benutzerrollen",
        "webPremiumF3": "Erweitertes Admin-Panel",
        "webPremiumF4": "SEO Pro",
        "webPremiumF5": "AI Vector im Panel",
        "webPremiumF6": "Priorisierter Support",
        "webPremiumF7": "Erweiterte Formulare",
        "webPremiumF8": "Skalierbare Architektur",
        "webPremiumF9": "Premium Design",
        "webPremiumF10": "Premium Motion",
        "webPremiumF11": "3D / Lottie / Video Hero — wenn es dem Projekt dient",
        "compareSiteType": "Website-Typ",
        "compareDesign": "Design",
        "compareMotion": "Animationen",
        "comparePages": "Website-Typ",
        "compareVal_typeLanding": "Landing oder kompakt",
        "compareVal_typeMulti": "Landing oder mehrseitig",
        "compareVal_typeCustom": "Individuelle Architektur",
        "compareVal_seoBasic": "Basis",
        "compareVal_seoExtended": "Erweitert",
        "compareVal_seoPro": "SEO Pro",
        "compareVal_designModern": "Modern",
        "compareVal_designBusiness": "Business Visual",
        "compareVal_designPremium": "Premium Visual",
        "compareVal_motionBasic": "Basis",
        "compareVal_motionRich": "Erweitert",
        "compareVal_motionPremium": "Premium + 3D/Video*",
        "compareVal_pages5": "Landing oder kompakt",
        "compareVal_pagesMulti": "Landing oder mehrseitig",
        "compareVal_pagesExtra": "Individuell",
    },
    "en": {
        "diffBasic1": "€199: modern responsive site — landing or compact company site",
        "diffBasic2": "Contact form, Impressum, privacy, basic SEO, Maps & chat",
        "diffBasic3": "Go live fast — no admin panel; Business/Premium = richer visuals & CMS",
        "webBasic": "Website Starter",
        "webBasicBlurb": "€199 one-time — modern responsive site for a fast online launch. Ideal for small businesses, specialists and company presentation.",
        "webBusiness": "Business Website",
        "webBusinessBlurb": "€399 one-time — full site with admin panel. Edit text and images yourself — plus Business Visual Pack.",
        "webPremium": "Premium Website",
        "webPremiumBlurb": "€699 one-time — maximum tier: Premium Design & Motion, SEO Pro, AI Vector, roles and priority support.",
        "webBasicF1": "Modern design",
        "webBasicF2": "Responsive (phone & tablet)",
        "webBasicF3": "Contact form",
        "webBasicF4": "Google Maps",
        "webBasicF5": "WhatsApp / Telegram / social",
        "webBasicF6": "Imprint & Privacy Policy",
        "webBasicF7": "Basic SEO",
        "webBasicF8": "Fast load speed",
        "webBasicF9": "Landing page or compact company site",
        "webBasicF10": "No admin panel",
        "webBusinessF1": "Everything in Starter",
        "webBusinessF2": "Admin panel",
        "webBusinessF3": "Edit pages",
        "webBusinessF4": "Upload images",
        "webBusinessF5": "Blog / News",
        "webBusinessF6": "Analytics",
        "webBusinessF7": "Content management",
        "webBusinessF8": "Contact forms",
        "webBusinessF9": "One-page or multi-page — per project",
        "webBusinessF10": "Business Visual Pack (Hero, motion, assets)",
        "webPremiumF1": "Everything in Business",
        "webPremiumF2": "User roles",
        "webPremiumF3": "Extended admin panel",
        "webPremiumF4": "SEO Pro",
        "webPremiumF5": "AI Vector in the panel",
        "webPremiumF6": "Priority support",
        "webPremiumF7": "Advanced forms",
        "webPremiumF8": "Scalable architecture",
        "webPremiumF9": "Premium Design",
        "webPremiumF10": "Premium Motion",
        "webPremiumF11": "3D / Lottie / Video Hero — when it fits the project",
        "compareSiteType": "Site type",
        "compareDesign": "Design",
        "compareMotion": "Motion",
        "comparePages": "Site type",
        "compareVal_typeLanding": "Landing or compact",
        "compareVal_typeMulti": "Landing or multi-page",
        "compareVal_typeCustom": "Custom architecture",
        "compareVal_seoBasic": "Basic",
        "compareVal_seoExtended": "Extended",
        "compareVal_seoPro": "SEO Pro",
        "compareVal_designModern": "Modern",
        "compareVal_designBusiness": "Business Visual",
        "compareVal_designPremium": "Premium Visual",
        "compareVal_motionBasic": "Basic",
        "compareVal_motionRich": "Extended",
        "compareVal_motionPremium": "Premium + 3D/Video*",
        "compareVal_pages5": "Landing or compact",
        "compareVal_pagesMulti": "Landing or multi-page",
        "compareVal_pagesExtra": "Custom",
    },
    "ru": {
        "diffBasic1": "199 €: современный адаптивный сайт — лендинг или компактный сайт",
        "diffBasic2": "Форма, Impressum, Privacy, базовое SEO, Maps и чат",
        "diffBasic3": "Быстрый выход в онлайн — без админки; Business/Premium = визуал и CMS",
        "webBasic": "Website Starter",
        "webBasicBlurb": "199 € разово — современный адаптивный сайт для быстрого старта. Для малого бизнеса, специалистов и презентации компании.",
        "webBusiness": "Business Website",
        "webBusinessBlurb": "399 € разово — полноценный сайт с панелью управления. Тексты и фото сами — плюс Business Visual Pack.",
        "webPremium": "Premium Website",
        "webPremiumBlurb": "699 € разово — максимум: Premium Design & Motion, SEO Pro, AI Vector, роли и приоритетная поддержка.",
        "webBasicF1": "Современный дизайн",
        "webBasicF2": "Адаптация под телефоны и планшеты",
        "webBasicF3": "Контактная форма",
        "webBasicF4": "Google Maps",
        "webBasicF5": "WhatsApp / Telegram / соцсети",
        "webBasicF6": "Imprint и Privacy Policy",
        "webBasicF7": "Базовая SEO-оптимизация",
        "webBasicF8": "Высокая скорость загрузки",
        "webBasicF9": "Landing или небольшой корпоративный сайт",
        "webBasicF10": "Без панели управления",
        "webBusinessF1": "Всё из Starter",
        "webBusinessF2": "Панель управления",
        "webBusinessF3": "Редактирование страниц",
        "webBusinessF4": "Загрузка изображений",
        "webBusinessF5": "Блог / Новости",
        "webBusinessF6": "Аналитика",
        "webBusinessF7": "Управление контентом",
        "webBusinessF8": "Формы обратной связи",
        "webBusinessF9": "Одно- или многостраничный — по проекту",
        "webBusinessF10": "Business Visual Pack (Hero, анимации, ассеты)",
        "webPremiumF1": "Всё из Business",
        "webPremiumF2": "Роли пользователей",
        "webPremiumF3": "Расширенная панель управления",
        "webPremiumF4": "SEO Pro",
        "webPremiumF5": "AI Vector в панели",
        "webPremiumF6": "Приоритетная поддержка",
        "webPremiumF7": "Расширенные формы",
        "webPremiumF8": "Масштабируемая архитектура",
        "webPremiumF9": "Premium Design",
        "webPremiumF10": "Premium Motion",
        "webPremiumF11": "3D / Lottie / Video Hero — если уместно проекту",
        "compareSiteType": "Тип сайта",
        "compareDesign": "Дизайн",
        "compareMotion": "Анимации",
        "comparePages": "Тип сайта",
        "compareVal_typeLanding": "Landing или компактный",
        "compareVal_typeMulti": "Landing или многостраничный",
        "compareVal_typeCustom": "Индивидуальная архитектура",
        "compareVal_seoBasic": "Базовое",
        "compareVal_seoExtended": "Расширенное",
        "compareVal_seoPro": "SEO Pro",
        "compareVal_designModern": "Современный",
        "compareVal_designBusiness": "Business Visual",
        "compareVal_designPremium": "Premium Visual",
        "compareVal_motionBasic": "Базовые",
        "compareVal_motionRich": "Расширенные",
        "compareVal_motionPremium": "Premium + 3D/Video*",
        "compareVal_pages5": "Landing или компактный",
        "compareVal_pagesMulti": "Landing или многостраничный",
        "compareVal_pagesExtra": "Индивидуально",
    },
}


def patch_locale(lang: str, mapping: dict[str, str]) -> None:
    path = ROOT / lang / "site.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    # top-level diff keys
    for k in ("diffBasic1", "diffBasic2", "diffBasic3"):
        if k in mapping and k in data:
            data[k] = mapping[k]
    pricing = data.setdefault("appStore", {}).setdefault("pricing", {})
    for k, v in mapping.items():
        if k.startswith("diff"):
            continue
        pricing[k] = v
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"patched {path}")


def main() -> None:
    for lang, mapping in PATCH.items():
        patch_locale(lang, mapping)


if __name__ == "__main__":
    main()
