"""Professional HTML rendering for business conclusions — no raw Markdown in browser."""

from __future__ import annotations

import html
import re


def _inline(text: str) -> str:
    escaped = html.escape(text)
    return re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", escaped)


def markdown_to_simple_html(md: str) -> str:
    """Minimal Markdown → HTML for controlled report templates."""
    out: list[str] = []
    in_ul = False

    def close_ul() -> None:
        nonlocal in_ul
        if in_ul:
            out.append("</ul>")
            in_ul = False

    for raw in md.splitlines():
        line = raw.rstrip()
        if not line.strip():
            close_ul()
            continue
        if line.startswith("# "):
            close_ul()
            out.append(f"<h1>{_inline(line[2:])}</h1>")
        elif line.startswith("## "):
            close_ul()
            out.append(f"<h2>{_inline(line[3:])}</h2>")
        elif line.startswith("### "):
            close_ul()
            out.append(f"<h3>{_inline(line[4:])}</h3>")
        elif line.startswith("---"):
            close_ul()
            out.append("<hr/>")
        elif line.startswith("- "):
            if not in_ul:
                out.append("<ul>")
                in_ul = True
            out.append(f"<li>{_inline(line[2:])}</li>")
        elif line.startswith("> "):
            close_ul()
            out.append(f"<blockquote>{_inline(line[2:])}</blockquote>")
        else:
            close_ul()
            out.append(f"<p>{_inline(line)}</p>")

    close_ul()
    return "\n".join(out)


_VIRTUS_REPORT_CSS = """
:root {
  color-scheme: dark;
  --bg: #0b0f1a;
  --card: #121829;
  --text: #e8ecf4;
  --muted: #9aa3b5;
  --accent: #6d8cff;
  --border: rgba(255,255,255,0.08);
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: "Segoe UI", system-ui, -apple-system, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.55;
  padding: 1.25rem;
}
.wrap {
  max-width: 820px;
  margin: 0 auto;
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 16px;
  padding: 1.75rem 2rem 2.5rem;
  box-shadow: 0 24px 80px rgba(0,0,0,0.35);
}
.brand {
  font-size: 0.7rem;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: var(--accent);
  margin-bottom: 1.25rem;
  font-weight: 700;
}
h1 { font-size: 1.65rem; margin: 0 0 1rem; line-height: 1.25; }
h2 {
  font-size: 1.1rem;
  margin: 1.75rem 0 0.75rem;
  padding-top: 0.5rem;
  border-top: 1px solid var(--border);
  color: #c5d0ff;
}
h3 { font-size: 0.95rem; margin: 1rem 0 0.5rem; color: var(--muted); }
p, li { font-size: 0.92rem; color: var(--text); }
ul { margin: 0.25rem 0 0.75rem; padding-left: 1.25rem; }
li { margin: 0.35rem 0; }
hr { border: none; border-top: 1px solid var(--border); margin: 1.25rem 0; }
blockquote {
  margin: 0.5rem 0;
  padding: 0.65rem 0.9rem;
  border-left: 3px solid var(--accent);
  background: rgba(109,140,255,0.08);
  border-radius: 0 8px 8px 0;
  color: var(--muted);
  font-size: 0.88rem;
}
strong { color: #fff; font-weight: 600; }
.footer {
  margin-top: 2rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border);
  font-size: 0.75rem;
  color: var(--muted);
}
@media (max-width: 640px) {
  body { padding: 0.75rem; }
  .wrap { padding: 1.25rem 1rem 1.75rem; border-radius: 12px; }
  h1 { font-size: 1.35rem; }
}
"""


def wrap_report_html(body_html: str, *, title: str = "Business Conclusion") -> str:
    safe_title = html.escape(title)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>{safe_title} — Vector</title>
  <style>{_VIRTUS_REPORT_CSS}</style>
</head>
<body>
  <div class="wrap">
    <div class="brand">Vector · Virtus Core</div>
    {body_html}
    <div class="footer">Professional business conclusion — generated by Vector execution layer.</div>
  </div>
</body>
</html>"""


def render_report_html_from_markdown(md: str, *, title: str = "Business Conclusion") -> str:
    return wrap_report_html(markdown_to_simple_html(md), title=title)
